=begin
#Shipeasy Admin API

#REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Shipeasy::Admin::Generated
  # Body for `POST /api/admin/gates`. At minimum supply `name`; everything else has sensible defaults.
  class CreateGateRequest < ApiModelBase
    # Stable gate key used by SDKs (`Shipeasy.checkGate(user, '<name>')`). Single segment or `folder.name`. Lowercase letters, digits, `_` or `-`; max 128 chars. Immutable after create — rename = delete + recreate.
    attr_accessor :name

    # Master switch. Defaults to `true`. Set `false` to create the gate disabled (evaluates to `false` regardless of rules/rollout); flip on via `POST /{id}/enable` or PATCH.
    attr_accessor :enabled

    # Initial rollout in **basis points** (0–10000 = 0%–100%) — `100` here means **1%**, not 100%. Use `rollout_percent` (0–100) below if you'd rather think in percent. Use `0` to create the gate dark and ramp via PATCH after deploy validation.
    attr_accessor :rollout_pct

    # Initial rollout as a **percentage** (0–100, fractional ok). Friendlier alias for `rollout_pct`; converted internally to basis points (e.g. `100` here = 10000 bp = 100%). If both `rollout_pct` and `rollout_percent` are set, `rollout_percent` wins.
    attr_accessor :rollout_percent

    # Targeting predicates. AND-combined. If non-empty, the gate returns `true` only for callers that satisfy every rule **and** fall under `rollout_pct`.
    attr_accessor :rules

    # Hash salt for percentage bucketing. Auto-generated if omitted. Provide explicitly to keep a gate's buckets stable across delete/recreate. **Immutable after create** — there is no PATCH for `salt` because changing it would re-bucket every caller.
    attr_accessor :salt

    # Optional gatekeeper stack. When provided, takes precedence over `rules` + `rollout_pct` at evaluation time. Omit (or pass `null`) for a flat gate.
    attr_accessor :stack

    # Human-readable title shown in the dashboard. Free-form, no key format constraint.
    attr_accessor :title

    # Long-form description / runbook. Markdown is rendered in the dashboard.
    attr_accessor :description

    # Optional folder name used to group items in the dashboard. Part of the SDK lookup key: an item in folder `checkout` named `new-cart` is referenced as `checkout/new-cart` from the SDK.
    attr_accessor :folder

    # Group label for dashboard organisation (e.g. team or product area).
    attr_accessor :group

    # Owner contact. Displayed verbatim; not used for auth.
    attr_accessor :owner_email

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'enabled' => :'enabled',
        :'rollout_pct' => :'rollout_pct',
        :'rollout_percent' => :'rollout_percent',
        :'rules' => :'rules',
        :'salt' => :'salt',
        :'stack' => :'stack',
        :'title' => :'title',
        :'description' => :'description',
        :'folder' => :'folder',
        :'group' => :'group',
        :'owner_email' => :'owner_email'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'enabled' => :'Boolean',
        :'rollout_pct' => :'Integer',
        :'rollout_percent' => :'Float',
        :'rules' => :'Array<ListGatesResponseDataInnerRulesInner>',
        :'salt' => :'String',
        :'stack' => :'Array<ListGatesResponseDataInnerStackInner>',
        :'title' => :'String',
        :'description' => :'String',
        :'folder' => :'String',
        :'group' => :'String',
        :'owner_email' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'stack',
        :'folder',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Shipeasy::Admin::Generated::CreateGateRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Shipeasy::Admin::Generated::CreateGateRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'enabled')
        self.enabled = attributes[:'enabled']
      else
        self.enabled = true
      end

      if attributes.key?(:'rollout_pct')
        self.rollout_pct = attributes[:'rollout_pct']
      else
        self.rollout_pct = 0
      end

      if attributes.key?(:'rollout_percent')
        self.rollout_percent = attributes[:'rollout_percent']
      end

      if attributes.key?(:'rules')
        if (value = attributes[:'rules']).is_a?(Array)
          self.rules = value
        end
      else
        self.rules = nil
      end

      if attributes.key?(:'salt')
        self.salt = attributes[:'salt']
      end

      if attributes.key?(:'stack')
        if (value = attributes[:'stack']).is_a?(Array)
          self.stack = value
        end
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'folder')
        self.folder = attributes[:'folder']
      end

      if attributes.key?(:'group')
        self.group = attributes[:'group']
      end

      if attributes.key?(:'owner_email')
        self.owner_email = attributes[:'owner_email']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 128
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 128.')
      end

      pattern = Regexp.new(/^[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?)?$/)
      if @name !~ pattern
        invalid_properties.push("invalid value for \"name\", must conform to the pattern #{pattern}.")
      end

      if @enabled.nil?
        invalid_properties.push('invalid value for "enabled", enabled cannot be nil.')
      end

      if @rollout_pct.nil?
        invalid_properties.push('invalid value for "rollout_pct", rollout_pct cannot be nil.')
      end

      if @rollout_pct > 10000
        invalid_properties.push('invalid value for "rollout_pct", must be smaller than or equal to 10000.')
      end

      if @rollout_pct < 0
        invalid_properties.push('invalid value for "rollout_pct", must be greater than or equal to 0.')
      end

      if !@rollout_percent.nil? && @rollout_percent > 100
        invalid_properties.push('invalid value for "rollout_percent", must be smaller than or equal to 100.')
      end

      if !@rollout_percent.nil? && @rollout_percent < 0
        invalid_properties.push('invalid value for "rollout_percent", must be greater than or equal to 0.')
      end

      if @rules.nil?
        invalid_properties.push('invalid value for "rules", rules cannot be nil.')
      end

      if !@salt.nil? && @salt.to_s.length > 64
        invalid_properties.push('invalid value for "salt", the character length must be smaller than or equal to 64.')
      end

      if !@salt.nil? && @salt.to_s.length < 1
        invalid_properties.push('invalid value for "salt", the character length must be greater than or equal to 1.')
      end

      if !@title.nil? && @title.to_s.length > 140
        invalid_properties.push('invalid value for "title", the character length must be smaller than or equal to 140.')
      end

      if !@description.nil? && @description.to_s.length > 2000
        invalid_properties.push('invalid value for "description", the character length must be smaller than or equal to 2000.')
      end

      if !@folder.nil? && @folder.to_s.length > 256
        invalid_properties.push('invalid value for "folder", the character length must be smaller than or equal to 256.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_-]+$/)
      if !@folder.nil? && @folder !~ pattern
        invalid_properties.push("invalid value for \"folder\", must conform to the pattern #{pattern}.")
      end

      if !@group.nil? && @group.to_s.length > 64
        invalid_properties.push('invalid value for "group", the character length must be smaller than or equal to 64.')
      end

      if !@owner_email.nil? && @owner_email.to_s.length > 190
        invalid_properties.push('invalid value for "owner_email", the character length must be smaller than or equal to 190.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @name.nil?
      return false if @name.to_s.length > 128
      return false if @name !~ Regexp.new(/^[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?)?$/)
      return false if @enabled.nil?
      return false if @rollout_pct.nil?
      return false if @rollout_pct > 10000
      return false if @rollout_pct < 0
      return false if !@rollout_percent.nil? && @rollout_percent > 100
      return false if !@rollout_percent.nil? && @rollout_percent < 0
      return false if @rules.nil?
      return false if !@salt.nil? && @salt.to_s.length > 64
      return false if !@salt.nil? && @salt.to_s.length < 1
      return false if !@title.nil? && @title.to_s.length > 140
      return false if !@description.nil? && @description.to_s.length > 2000
      return false if !@folder.nil? && @folder.to_s.length > 256
      return false if !@folder.nil? && @folder !~ Regexp.new(/^[a-zA-Z0-9_-]+$/)
      return false if !@group.nil? && @group.to_s.length > 64
      return false if !@owner_email.nil? && @owner_email.to_s.length > 190
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 128
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 128.'
      end

      pattern = Regexp.new(/^[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?)?$/)
      if name !~ pattern
        fail ArgumentError, "invalid value for \"name\", must conform to the pattern #{pattern}."
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] enabled Value to be assigned
    def enabled=(enabled)
      if enabled.nil?
        fail ArgumentError, 'enabled cannot be nil'
      end

      @enabled = enabled
    end

    # Custom attribute writer method with validation
    # @param [Object] rollout_pct Value to be assigned
    def rollout_pct=(rollout_pct)
      if rollout_pct.nil?
        fail ArgumentError, 'rollout_pct cannot be nil'
      end

      if rollout_pct > 10000
        fail ArgumentError, 'invalid value for "rollout_pct", must be smaller than or equal to 10000.'
      end

      if rollout_pct < 0
        fail ArgumentError, 'invalid value for "rollout_pct", must be greater than or equal to 0.'
      end

      @rollout_pct = rollout_pct
    end

    # Custom attribute writer method with validation
    # @param [Object] rollout_percent Value to be assigned
    def rollout_percent=(rollout_percent)
      if rollout_percent.nil?
        fail ArgumentError, 'rollout_percent cannot be nil'
      end

      if rollout_percent > 100
        fail ArgumentError, 'invalid value for "rollout_percent", must be smaller than or equal to 100.'
      end

      if rollout_percent < 0
        fail ArgumentError, 'invalid value for "rollout_percent", must be greater than or equal to 0.'
      end

      @rollout_percent = rollout_percent
    end

    # Custom attribute writer method with validation
    # @param [Object] rules Value to be assigned
    def rules=(rules)
      if rules.nil?
        fail ArgumentError, 'rules cannot be nil'
      end

      @rules = rules
    end

    # Custom attribute writer method with validation
    # @param [Object] salt Value to be assigned
    def salt=(salt)
      if salt.nil?
        fail ArgumentError, 'salt cannot be nil'
      end

      if salt.to_s.length > 64
        fail ArgumentError, 'invalid value for "salt", the character length must be smaller than or equal to 64.'
      end

      if salt.to_s.length < 1
        fail ArgumentError, 'invalid value for "salt", the character length must be greater than or equal to 1.'
      end

      @salt = salt
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if title.nil?
        fail ArgumentError, 'title cannot be nil'
      end

      if title.to_s.length > 140
        fail ArgumentError, 'invalid value for "title", the character length must be smaller than or equal to 140.'
      end

      @title = title
    end

    # Custom attribute writer method with validation
    # @param [Object] description Value to be assigned
    def description=(description)
      if description.nil?
        fail ArgumentError, 'description cannot be nil'
      end

      if description.to_s.length > 2000
        fail ArgumentError, 'invalid value for "description", the character length must be smaller than or equal to 2000.'
      end

      @description = description
    end

    # Custom attribute writer method with validation
    # @param [Object] folder Value to be assigned
    def folder=(folder)
      if !folder.nil? && folder.to_s.length > 256
        fail ArgumentError, 'invalid value for "folder", the character length must be smaller than or equal to 256.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_-]+$/)
      if !folder.nil? && folder !~ pattern
        fail ArgumentError, "invalid value for \"folder\", must conform to the pattern #{pattern}."
      end

      @folder = folder
    end

    # Custom attribute writer method with validation
    # @param [Object] group Value to be assigned
    def group=(group)
      if group.nil?
        fail ArgumentError, 'group cannot be nil'
      end

      if group.to_s.length > 64
        fail ArgumentError, 'invalid value for "group", the character length must be smaller than or equal to 64.'
      end

      @group = group
    end

    # Custom attribute writer method with validation
    # @param [Object] owner_email Value to be assigned
    def owner_email=(owner_email)
      if owner_email.nil?
        fail ArgumentError, 'owner_email cannot be nil'
      end

      if owner_email.to_s.length > 190
        fail ArgumentError, 'invalid value for "owner_email", the character length must be smaller than or equal to 190.'
      end

      @owner_email = owner_email
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          enabled == o.enabled &&
          rollout_pct == o.rollout_pct &&
          rollout_percent == o.rollout_percent &&
          rules == o.rules &&
          salt == o.salt &&
          stack == o.stack &&
          title == o.title &&
          description == o.description &&
          folder == o.folder &&
          group == o.group &&
          owner_email == o.owner_email
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, enabled, rollout_pct, rollout_percent, rules, salt, stack, title, description, folder, group, owner_email].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
