=begin
#Shipeasy Admin API

#REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Shipeasy::Admin::Generated
  class CreateAlertRuleRequest < ApiModelBase
    # Human label for the rule, shown on the alert and the rules list.
    attr_accessor :name

    # Id of the metric to evaluate.
    attr_accessor :metric_id

    # How the metric value is compared to the threshold (gt/gte/lt/lte).
    attr_accessor :comparator

    # Threshold the metric value is compared against.
    attr_accessor :threshold

    # Lookback window (hours) the metric is aggregated over. 1–720.
    attr_accessor :window_hours

    # Severity of the raised alert.
    attr_accessor :severity

    # Whether the rule is evaluated by the cron.
    attr_accessor :enabled

    attr_accessor :notify

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'metric_id' => :'metricId',
        :'comparator' => :'comparator',
        :'threshold' => :'threshold',
        :'window_hours' => :'windowHours',
        :'severity' => :'severity',
        :'enabled' => :'enabled',
        :'notify' => :'notify'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'metric_id' => :'String',
        :'comparator' => :'String',
        :'threshold' => :'Float',
        :'window_hours' => :'Integer',
        :'severity' => :'String',
        :'enabled' => :'Boolean',
        :'notify' => :'ListAlertRulesResponseInnerNotify'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'notify'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Shipeasy::Admin::Generated::CreateAlertRuleRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Shipeasy::Admin::Generated::CreateAlertRuleRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'metric_id')
        self.metric_id = attributes[:'metric_id']
      else
        self.metric_id = nil
      end

      if attributes.key?(:'comparator')
        self.comparator = attributes[:'comparator']
      else
        self.comparator = nil
      end

      if attributes.key?(:'threshold')
        self.threshold = attributes[:'threshold']
      else
        self.threshold = nil
      end

      if attributes.key?(:'window_hours')
        self.window_hours = attributes[:'window_hours']
      else
        self.window_hours = 24
      end

      if attributes.key?(:'severity')
        self.severity = attributes[:'severity']
      else
        self.severity = 'warn'
      end

      if attributes.key?(:'enabled')
        self.enabled = attributes[:'enabled']
      else
        self.enabled = true
      end

      if attributes.key?(:'notify')
        self.notify = attributes[:'notify']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 120
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 120.')
      end

      if @name.to_s.length < 1
        invalid_properties.push('invalid value for "name", the character length must be greater than or equal to 1.')
      end

      if @metric_id.nil?
        invalid_properties.push('invalid value for "metric_id", metric_id cannot be nil.')
      end

      if @metric_id.to_s.length < 1
        invalid_properties.push('invalid value for "metric_id", the character length must be greater than or equal to 1.')
      end

      if @comparator.nil?
        invalid_properties.push('invalid value for "comparator", comparator cannot be nil.')
      end

      if @threshold.nil?
        invalid_properties.push('invalid value for "threshold", threshold cannot be nil.')
      end

      if @window_hours.nil?
        invalid_properties.push('invalid value for "window_hours", window_hours cannot be nil.')
      end

      if @window_hours > 720
        invalid_properties.push('invalid value for "window_hours", must be smaller than or equal to 720.')
      end

      if @window_hours < 1
        invalid_properties.push('invalid value for "window_hours", must be greater than or equal to 1.')
      end

      if @severity.nil?
        invalid_properties.push('invalid value for "severity", severity cannot be nil.')
      end

      if @enabled.nil?
        invalid_properties.push('invalid value for "enabled", enabled cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @name.nil?
      return false if @name.to_s.length > 120
      return false if @name.to_s.length < 1
      return false if @metric_id.nil?
      return false if @metric_id.to_s.length < 1
      return false if @comparator.nil?
      comparator_validator = EnumAttributeValidator.new('String', ["gt", "gte", "lt", "lte"])
      return false unless comparator_validator.valid?(@comparator)
      return false if @threshold.nil?
      return false if @window_hours.nil?
      return false if @window_hours > 720
      return false if @window_hours < 1
      return false if @severity.nil?
      severity_validator = EnumAttributeValidator.new('String', ["danger", "warn", "info"])
      return false unless severity_validator.valid?(@severity)
      return false if @enabled.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 120
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 120.'
      end

      if name.to_s.length < 1
        fail ArgumentError, 'invalid value for "name", the character length must be greater than or equal to 1.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] metric_id Value to be assigned
    def metric_id=(metric_id)
      if metric_id.nil?
        fail ArgumentError, 'metric_id cannot be nil'
      end

      if metric_id.to_s.length < 1
        fail ArgumentError, 'invalid value for "metric_id", the character length must be greater than or equal to 1.'
      end

      @metric_id = metric_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] comparator Object to be assigned
    def comparator=(comparator)
      validator = EnumAttributeValidator.new('String', ["gt", "gte", "lt", "lte"])
      unless validator.valid?(comparator)
        fail ArgumentError, "invalid value for \"comparator\", must be one of #{validator.allowable_values}."
      end
      @comparator = comparator
    end

    # Custom attribute writer method with validation
    # @param [Object] threshold Value to be assigned
    def threshold=(threshold)
      if threshold.nil?
        fail ArgumentError, 'threshold cannot be nil'
      end

      @threshold = threshold
    end

    # Custom attribute writer method with validation
    # @param [Object] window_hours Value to be assigned
    def window_hours=(window_hours)
      if window_hours.nil?
        fail ArgumentError, 'window_hours cannot be nil'
      end

      if window_hours > 720
        fail ArgumentError, 'invalid value for "window_hours", must be smaller than or equal to 720.'
      end

      if window_hours < 1
        fail ArgumentError, 'invalid value for "window_hours", must be greater than or equal to 1.'
      end

      @window_hours = window_hours
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] severity Object to be assigned
    def severity=(severity)
      validator = EnumAttributeValidator.new('String', ["danger", "warn", "info"])
      unless validator.valid?(severity)
        fail ArgumentError, "invalid value for \"severity\", must be one of #{validator.allowable_values}."
      end
      @severity = severity
    end

    # Custom attribute writer method with validation
    # @param [Object] enabled Value to be assigned
    def enabled=(enabled)
      if enabled.nil?
        fail ArgumentError, 'enabled cannot be nil'
      end

      @enabled = enabled
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          metric_id == o.metric_id &&
          comparator == o.comparator &&
          threshold == o.threshold &&
          window_hours == o.window_hours &&
          severity == o.severity &&
          enabled == o.enabled &&
          notify == o.notify
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, metric_id, comparator, threshold, window_hours, severity, enabled, notify].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
