=begin
#Shipeasy Admin API

#REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Shipeasy::Admin::Generated
  # Body for `POST /api/admin/metrics`. Requires `name`, `event_name`, and exactly one of `query` / `query_ir`.
  class CreateMetricRequest < ApiModelBase
    # Stable metric key. Single segment or `folder.name`; lowercase letters, digits, `_`/`-`; max 128 chars.
    attr_accessor :name

    # Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`).
    attr_accessor :folder

    # Source event the query reads from.
    attr_accessor :event_name

    # Metric query DSL string, e.g. `sum(purchase, amount)`. Provide this OR `query_ir`.
    attr_accessor :query

    attr_accessor :query_ir

    # Winsorise percentile (1–99) to clamp outliers. Defaults to 99.
    attr_accessor :winsorize_pct

    # Minimum detectable effect (relative, 0–1) for power planning. `null` to omit.
    attr_accessor :min_detectable_effect

    # Desired direction of movement. `higher_better` (default), `lower_better`, or `neutral` (guardrail).
    attr_accessor :direction

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'folder' => :'folder',
        :'event_name' => :'event_name',
        :'query' => :'query',
        :'query_ir' => :'query_ir',
        :'winsorize_pct' => :'winsorize_pct',
        :'min_detectable_effect' => :'min_detectable_effect',
        :'direction' => :'direction'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'folder' => :'String',
        :'event_name' => :'String',
        :'query' => :'String',
        :'query_ir' => :'ListMetricsResponseInnerQueryIr',
        :'winsorize_pct' => :'Integer',
        :'min_detectable_effect' => :'Float',
        :'direction' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'folder',
        :'min_detectable_effect',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Shipeasy::Admin::Generated::CreateMetricRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Shipeasy::Admin::Generated::CreateMetricRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'folder')
        self.folder = attributes[:'folder']
      end

      if attributes.key?(:'event_name')
        self.event_name = attributes[:'event_name']
      else
        self.event_name = nil
      end

      if attributes.key?(:'query')
        self.query = attributes[:'query']
      end

      if attributes.key?(:'query_ir')
        self.query_ir = attributes[:'query_ir']
      end

      if attributes.key?(:'winsorize_pct')
        self.winsorize_pct = attributes[:'winsorize_pct']
      else
        self.winsorize_pct = 99
      end

      if attributes.key?(:'min_detectable_effect')
        self.min_detectable_effect = attributes[:'min_detectable_effect']
      end

      if attributes.key?(:'direction')
        self.direction = attributes[:'direction']
      else
        self.direction = 'higher_better'
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 128
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 128.')
      end

      pattern = Regexp.new(/^[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?)?$/)
      if @name !~ pattern
        invalid_properties.push("invalid value for \"name\", must conform to the pattern #{pattern}.")
      end

      if !@folder.nil? && @folder.to_s.length > 256
        invalid_properties.push('invalid value for "folder", the character length must be smaller than or equal to 256.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_-]+$/)
      if !@folder.nil? && @folder !~ pattern
        invalid_properties.push("invalid value for \"folder\", must conform to the pattern #{pattern}.")
      end

      if @event_name.nil?
        invalid_properties.push('invalid value for "event_name", event_name cannot be nil.')
      end

      if @event_name.to_s.length < 1
        invalid_properties.push('invalid value for "event_name", the character length must be greater than or equal to 1.')
      end

      if !@query.nil? && @query.to_s.length > 4096
        invalid_properties.push('invalid value for "query", the character length must be smaller than or equal to 4096.')
      end

      if !@query.nil? && @query.to_s.length < 1
        invalid_properties.push('invalid value for "query", the character length must be greater than or equal to 1.')
      end

      if !@winsorize_pct.nil? && @winsorize_pct > 99
        invalid_properties.push('invalid value for "winsorize_pct", must be smaller than or equal to 99.')
      end

      if !@winsorize_pct.nil? && @winsorize_pct < 1
        invalid_properties.push('invalid value for "winsorize_pct", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @name.nil?
      return false if @name.to_s.length > 128
      return false if @name !~ Regexp.new(/^[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?)?$/)
      return false if !@folder.nil? && @folder.to_s.length > 256
      return false if !@folder.nil? && @folder !~ Regexp.new(/^[a-zA-Z0-9_-]+$/)
      return false if @event_name.nil?
      return false if @event_name.to_s.length < 1
      return false if !@query.nil? && @query.to_s.length > 4096
      return false if !@query.nil? && @query.to_s.length < 1
      return false if !@winsorize_pct.nil? && @winsorize_pct > 99
      return false if !@winsorize_pct.nil? && @winsorize_pct < 1
      direction_validator = EnumAttributeValidator.new('String', ["higher_better", "lower_better", "neutral"])
      return false unless direction_validator.valid?(@direction)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 128
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 128.'
      end

      pattern = Regexp.new(/^[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9_-]*[a-z0-9])?)?$/)
      if name !~ pattern
        fail ArgumentError, "invalid value for \"name\", must conform to the pattern #{pattern}."
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] folder Value to be assigned
    def folder=(folder)
      if !folder.nil? && folder.to_s.length > 256
        fail ArgumentError, 'invalid value for "folder", the character length must be smaller than or equal to 256.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_-]+$/)
      if !folder.nil? && folder !~ pattern
        fail ArgumentError, "invalid value for \"folder\", must conform to the pattern #{pattern}."
      end

      @folder = folder
    end

    # Custom attribute writer method with validation
    # @param [Object] event_name Value to be assigned
    def event_name=(event_name)
      if event_name.nil?
        fail ArgumentError, 'event_name cannot be nil'
      end

      if event_name.to_s.length < 1
        fail ArgumentError, 'invalid value for "event_name", the character length must be greater than or equal to 1.'
      end

      @event_name = event_name
    end

    # Custom attribute writer method with validation
    # @param [Object] query Value to be assigned
    def query=(query)
      if query.nil?
        fail ArgumentError, 'query cannot be nil'
      end

      if query.to_s.length > 4096
        fail ArgumentError, 'invalid value for "query", the character length must be smaller than or equal to 4096.'
      end

      if query.to_s.length < 1
        fail ArgumentError, 'invalid value for "query", the character length must be greater than or equal to 1.'
      end

      @query = query
    end

    # Custom attribute writer method with validation
    # @param [Object] winsorize_pct Value to be assigned
    def winsorize_pct=(winsorize_pct)
      if winsorize_pct.nil?
        fail ArgumentError, 'winsorize_pct cannot be nil'
      end

      if winsorize_pct > 99
        fail ArgumentError, 'invalid value for "winsorize_pct", must be smaller than or equal to 99.'
      end

      if winsorize_pct < 1
        fail ArgumentError, 'invalid value for "winsorize_pct", must be greater than or equal to 1.'
      end

      @winsorize_pct = winsorize_pct
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] direction Object to be assigned
    def direction=(direction)
      validator = EnumAttributeValidator.new('String', ["higher_better", "lower_better", "neutral"])
      unless validator.valid?(direction)
        fail ArgumentError, "invalid value for \"direction\", must be one of #{validator.allowable_values}."
      end
      @direction = direction
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          folder == o.folder &&
          event_name == o.event_name &&
          query == o.query &&
          query_ir == o.query_ir &&
          winsorize_pct == o.winsorize_pct &&
          min_detectable_effect == o.min_detectable_effect &&
          direction == o.direction
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, folder, event_name, query, query_ir, winsorize_pct, min_detectable_effect, direction].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
