=begin
#Shipeasy Admin API (server-SDK surface)

#The slice of the Shipeasy admin API that the published server SDKs expose as their optional `AdminClient`. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Three capabilities, nothing else:  - **File a public ticket** — a bug or a feature request onto the project's ops queue. - **Toggle a kill switch** — flip the switch itself, or one of its named sub-switches, on one environment. - **Manage a flag's whitelist** — read, replace, add to, or remove from the allowlist that admits specific identities ahead of every targeting rule.  Everything else in the admin API is reachable through the Shipeasy CLI and MCP server, which speak the complete contract (`openapi.yaml`).

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Shipeasy::Admin::Generated
  class ErrorCode
    BAD_REQUEST = "BAD_REQUEST".freeze
    UNAUTHORIZED = "UNAUTHORIZED".freeze
    FORBIDDEN = "FORBIDDEN".freeze
    PLAN_REQUIRED = "PLAN_REQUIRED".freeze
    NOT_FOUND = "NOT_FOUND".freeze
    ALREADY_EXISTS = "ALREADY_EXISTS".freeze
    INVALID_TRANSITION = "INVALID_TRANSITION".freeze
    IMMUTABLE_FIELD = "IMMUTABLE_FIELD".freeze
    READ_ONLY = "READ_ONLY".freeze
    REFERENCED_IN_USE = "REFERENCED_IN_USE".freeze
    VALIDATION = "VALIDATION".freeze
    REFERENCED_NOT_FOUND = "REFERENCED_NOT_FOUND".freeze
    GROUPS_WEIGHT_SUM = "GROUPS_WEIGHT_SUM".freeze
    EVENT_PENDING = "EVENT_PENDING".freeze
    INTERNAL = "INTERNAL".freeze
    PLAN_LIMIT = "PLAN_LIMIT".freeze
    EXPERIMENT_NO_GOAL_METRIC = "EXPERIMENT_NO_GOAL_METRIC".freeze
    EXPERIMENT_ARCHIVED_RESTART = "EXPERIMENT_ARCHIVED_RESTART".freeze
    EXPERIMENT_RESTORE_INVALID = "EXPERIMENT_RESTORE_INVALID".freeze
    EXPERIMENT_NOT_RUNNING = "EXPERIMENT_NOT_RUNNING".freeze
    EXPERIMENT_RUNNING_ARCHIVE = "EXPERIMENT_RUNNING_ARCHIVE".freeze
    EXPERIMENT_IMMUTABLE_FIELD = "EXPERIMENT_IMMUTABLE_FIELD".freeze
    METRIC_NOT_FOUND = "METRIC_NOT_FOUND".freeze
    METRIC_UNKNOWN_ID = "METRIC_UNKNOWN_ID".freeze
    AGENT_NOT_CONNECTED = "AGENT_NOT_CONNECTED".freeze

    def self.all_vars
      @all_vars ||= [BAD_REQUEST, UNAUTHORIZED, FORBIDDEN, PLAN_REQUIRED, NOT_FOUND, ALREADY_EXISTS, INVALID_TRANSITION, IMMUTABLE_FIELD, READ_ONLY, REFERENCED_IN_USE, VALIDATION, REFERENCED_NOT_FOUND, GROUPS_WEIGHT_SUM, EVENT_PENDING, INTERNAL, PLAN_LIMIT, EXPERIMENT_NO_GOAL_METRIC, EXPERIMENT_ARCHIVED_RESTART, EXPERIMENT_RESTORE_INVALID, EXPERIMENT_NOT_RUNNING, EXPERIMENT_RUNNING_ARCHIVE, EXPERIMENT_IMMUTABLE_FIELD, METRIC_NOT_FOUND, METRIC_UNKNOWN_ID, AGENT_NOT_CONNECTED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ErrorCode.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ErrorCode"
    end
  end
end
