=begin
#Shipeasy Admin API

#REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Shipeasy::Admin::Generated
  # The project the caller's auth header resolves to. The shape is open — additional project fields may be present.
  class GetCurrentProjectResponse < ApiModelBase
    # Stable opaque project id.
    attr_accessor :id

    # Project name.
    attr_accessor :name

    # Project domain, or `null` if unset.
    attr_accessor :domain

    # Email of the account that owns the project.
    attr_accessor :owner_email

    # Billing plan tier.
    attr_accessor :plan

    # Project lifecycle status.
    attr_accessor :status

    # Stripe subscription status (`none`, `active`, `trialing`, `past_due`, …).
    attr_accessor :subscription_status

    # Billing cadence.
    attr_accessor :billing_interval

    # ISO-8601 end of the current billing period, or `null`.
    attr_accessor :current_period_end

    # ISO-8601 trial end, or `null` if not trialing.
    attr_accessor :trial_ends_at

    # `1` if the subscription is set to cancel at period end, else `0`.
    attr_accessor :cancel_at_period_end

    attr_accessor :module_translations

    attr_accessor :module_configs

    attr_accessor :module_gates

    attr_accessor :module_experiments

    attr_accessor :module_feedback

    # ISO-8601 timestamp of project creation.
    attr_accessor :created_at

    # ISO-8601 timestamp of last update.
    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'domain' => :'domain',
        :'owner_email' => :'ownerEmail',
        :'plan' => :'plan',
        :'status' => :'status',
        :'subscription_status' => :'subscriptionStatus',
        :'billing_interval' => :'billingInterval',
        :'current_period_end' => :'currentPeriodEnd',
        :'trial_ends_at' => :'trialEndsAt',
        :'cancel_at_period_end' => :'cancelAtPeriodEnd',
        :'module_translations' => :'moduleTranslations',
        :'module_configs' => :'moduleConfigs',
        :'module_gates' => :'moduleGates',
        :'module_experiments' => :'moduleExperiments',
        :'module_feedback' => :'moduleFeedback',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'domain' => :'String',
        :'owner_email' => :'String',
        :'plan' => :'String',
        :'status' => :'String',
        :'subscription_status' => :'String',
        :'billing_interval' => :'String',
        :'current_period_end' => :'String',
        :'trial_ends_at' => :'String',
        :'cancel_at_period_end' => :'Float',
        :'module_translations' => :'GetCurrentProjectResponseModuleTranslations',
        :'module_configs' => :'GetCurrentProjectResponseModuleTranslations',
        :'module_gates' => :'GetCurrentProjectResponseModuleTranslations',
        :'module_experiments' => :'GetCurrentProjectResponseModuleTranslations',
        :'module_feedback' => :'GetCurrentProjectResponseModuleTranslations',
        :'created_at' => :'String',
        :'updated_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'domain',
        :'current_period_end',
        :'trial_ends_at',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Shipeasy::Admin::Generated::GetCurrentProjectResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Shipeasy::Admin::Generated::GetCurrentProjectResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'domain')
        self.domain = attributes[:'domain']
      else
        self.domain = nil
      end

      if attributes.key?(:'owner_email')
        self.owner_email = attributes[:'owner_email']
      else
        self.owner_email = nil
      end

      if attributes.key?(:'plan')
        self.plan = attributes[:'plan']
      else
        self.plan = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'subscription_status')
        self.subscription_status = attributes[:'subscription_status']
      else
        self.subscription_status = nil
      end

      if attributes.key?(:'billing_interval')
        self.billing_interval = attributes[:'billing_interval']
      else
        self.billing_interval = nil
      end

      if attributes.key?(:'current_period_end')
        self.current_period_end = attributes[:'current_period_end']
      else
        self.current_period_end = nil
      end

      if attributes.key?(:'trial_ends_at')
        self.trial_ends_at = attributes[:'trial_ends_at']
      else
        self.trial_ends_at = nil
      end

      if attributes.key?(:'cancel_at_period_end')
        self.cancel_at_period_end = attributes[:'cancel_at_period_end']
      else
        self.cancel_at_period_end = nil
      end

      if attributes.key?(:'module_translations')
        self.module_translations = attributes[:'module_translations']
      else
        self.module_translations = nil
      end

      if attributes.key?(:'module_configs')
        self.module_configs = attributes[:'module_configs']
      else
        self.module_configs = nil
      end

      if attributes.key?(:'module_gates')
        self.module_gates = attributes[:'module_gates']
      else
        self.module_gates = nil
      end

      if attributes.key?(:'module_experiments')
        self.module_experiments = attributes[:'module_experiments']
      else
        self.module_experiments = nil
      end

      if attributes.key?(:'module_feedback')
        self.module_feedback = attributes[:'module_feedback']
      else
        self.module_feedback = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @owner_email.nil?
        invalid_properties.push('invalid value for "owner_email", owner_email cannot be nil.')
      end

      if @plan.nil?
        invalid_properties.push('invalid value for "plan", plan cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @subscription_status.nil?
        invalid_properties.push('invalid value for "subscription_status", subscription_status cannot be nil.')
      end

      if @billing_interval.nil?
        invalid_properties.push('invalid value for "billing_interval", billing_interval cannot be nil.')
      end

      if @cancel_at_period_end.nil?
        invalid_properties.push('invalid value for "cancel_at_period_end", cancel_at_period_end cannot be nil.')
      end

      if @module_translations.nil?
        invalid_properties.push('invalid value for "module_translations", module_translations cannot be nil.')
      end

      if @module_configs.nil?
        invalid_properties.push('invalid value for "module_configs", module_configs cannot be nil.')
      end

      if @module_gates.nil?
        invalid_properties.push('invalid value for "module_gates", module_gates cannot be nil.')
      end

      if @module_experiments.nil?
        invalid_properties.push('invalid value for "module_experiments", module_experiments cannot be nil.')
      end

      if @module_feedback.nil?
        invalid_properties.push('invalid value for "module_feedback", module_feedback cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @name.nil?
      return false if @owner_email.nil?
      return false if @plan.nil?
      plan_validator = EnumAttributeValidator.new('String', ["free", "paid"])
      return false unless plan_validator.valid?(@plan)
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["active", "inactive"])
      return false unless status_validator.valid?(@status)
      return false if @subscription_status.nil?
      return false if @billing_interval.nil?
      billing_interval_validator = EnumAttributeValidator.new('String', ["monthly", "annual"])
      return false unless billing_interval_validator.valid?(@billing_interval)
      return false if @cancel_at_period_end.nil?
      return false if @module_translations.nil?
      return false if @module_configs.nil?
      return false if @module_gates.nil?
      return false if @module_experiments.nil?
      return false if @module_feedback.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] owner_email Value to be assigned
    def owner_email=(owner_email)
      if owner_email.nil?
        fail ArgumentError, 'owner_email cannot be nil'
      end

      @owner_email = owner_email
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] plan Object to be assigned
    def plan=(plan)
      validator = EnumAttributeValidator.new('String', ["free", "paid"])
      unless validator.valid?(plan)
        fail ArgumentError, "invalid value for \"plan\", must be one of #{validator.allowable_values}."
      end
      @plan = plan
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["active", "inactive"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] subscription_status Value to be assigned
    def subscription_status=(subscription_status)
      if subscription_status.nil?
        fail ArgumentError, 'subscription_status cannot be nil'
      end

      @subscription_status = subscription_status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] billing_interval Object to be assigned
    def billing_interval=(billing_interval)
      validator = EnumAttributeValidator.new('String', ["monthly", "annual"])
      unless validator.valid?(billing_interval)
        fail ArgumentError, "invalid value for \"billing_interval\", must be one of #{validator.allowable_values}."
      end
      @billing_interval = billing_interval
    end

    # Custom attribute writer method with validation
    # @param [Object] cancel_at_period_end Value to be assigned
    def cancel_at_period_end=(cancel_at_period_end)
      if cancel_at_period_end.nil?
        fail ArgumentError, 'cancel_at_period_end cannot be nil'
      end

      @cancel_at_period_end = cancel_at_period_end
    end

    # Custom attribute writer method with validation
    # @param [Object] module_translations Value to be assigned
    def module_translations=(module_translations)
      if module_translations.nil?
        fail ArgumentError, 'module_translations cannot be nil'
      end

      @module_translations = module_translations
    end

    # Custom attribute writer method with validation
    # @param [Object] module_configs Value to be assigned
    def module_configs=(module_configs)
      if module_configs.nil?
        fail ArgumentError, 'module_configs cannot be nil'
      end

      @module_configs = module_configs
    end

    # Custom attribute writer method with validation
    # @param [Object] module_gates Value to be assigned
    def module_gates=(module_gates)
      if module_gates.nil?
        fail ArgumentError, 'module_gates cannot be nil'
      end

      @module_gates = module_gates
    end

    # Custom attribute writer method with validation
    # @param [Object] module_experiments Value to be assigned
    def module_experiments=(module_experiments)
      if module_experiments.nil?
        fail ArgumentError, 'module_experiments cannot be nil'
      end

      @module_experiments = module_experiments
    end

    # Custom attribute writer method with validation
    # @param [Object] module_feedback Value to be assigned
    def module_feedback=(module_feedback)
      if module_feedback.nil?
        fail ArgumentError, 'module_feedback cannot be nil'
      end

      @module_feedback = module_feedback
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          domain == o.domain &&
          owner_email == o.owner_email &&
          plan == o.plan &&
          status == o.status &&
          subscription_status == o.subscription_status &&
          billing_interval == o.billing_interval &&
          current_period_end == o.current_period_end &&
          trial_ends_at == o.trial_ends_at &&
          cancel_at_period_end == o.cancel_at_period_end &&
          module_translations == o.module_translations &&
          module_configs == o.module_configs &&
          module_gates == o.module_gates &&
          module_experiments == o.module_experiments &&
          module_feedback == o.module_feedback &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, domain, owner_email, plan, status, subscription_status, billing_interval, current_period_end, trial_ends_at, cancel_at_period_end, module_translations, module_configs, module_gates, module_experiments, module_feedback, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
