=begin
#Shipeasy Admin API

#REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Shipeasy::Admin::Generated
  class ListConfigsResponseDataInnerDraftsValue < ApiModelBase
    # ISO-8601 last-edit timestamp on the draft.
    attr_accessor :updated_at

    # Email/id of the actor who last edited the draft.
    attr_accessor :author_email

    # Published version the draft was forked from.
    attr_accessor :base_version

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'updated_at' => :'updatedAt',
        :'author_email' => :'authorEmail',
        :'base_version' => :'baseVersion'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'updated_at' => :'String',
        :'author_email' => :'String',
        :'base_version' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Shipeasy::Admin::Generated::ListConfigsResponseDataInnerDraftsValue` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Shipeasy::Admin::Generated::ListConfigsResponseDataInnerDraftsValue`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'author_email')
        self.author_email = attributes[:'author_email']
      else
        self.author_email = nil
      end

      if attributes.key?(:'base_version')
        self.base_version = attributes[:'base_version']
      else
        self.base_version = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      if @author_email.nil?
        invalid_properties.push('invalid value for "author_email", author_email cannot be nil.')
      end

      if @base_version.nil?
        invalid_properties.push('invalid value for "base_version", base_version cannot be nil.')
      end

      if @base_version > 9007199254740991
        invalid_properties.push('invalid value for "base_version", must be smaller than or equal to 9007199254740991.')
      end

      if @base_version < -9007199254740991
        invalid_properties.push('invalid value for "base_version", must be greater than or equal to -9007199254740991.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @updated_at.nil?
      return false if @author_email.nil?
      return false if @base_version.nil?
      return false if @base_version > 9007199254740991
      return false if @base_version < -9007199254740991
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Custom attribute writer method with validation
    # @param [Object] author_email Value to be assigned
    def author_email=(author_email)
      if author_email.nil?
        fail ArgumentError, 'author_email cannot be nil'
      end

      @author_email = author_email
    end

    # Custom attribute writer method with validation
    # @param [Object] base_version Value to be assigned
    def base_version=(base_version)
      if base_version.nil?
        fail ArgumentError, 'base_version cannot be nil'
      end

      if base_version > 9007199254740991
        fail ArgumentError, 'invalid value for "base_version", must be smaller than or equal to 9007199254740991.'
      end

      if base_version < -9007199254740991
        fail ArgumentError, 'invalid value for "base_version", must be greater than or equal to -9007199254740991.'
      end

      @base_version = base_version
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          updated_at == o.updated_at &&
          author_email == o.author_email &&
          base_version == o.base_version
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [updated_at, author_email, base_version].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
