=begin
#Shipeasy Admin API

#REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Shipeasy::Admin::Generated
  # Percentage-rollout sub-gate. Hashes `bucketBy` (default `userID`) with `salt` and returns `true` for `rolloutPct/10000` fraction of callers (or the ramp's effective % when `ramp` is set).
  class ListGatesResponseDataInnerStackInnerOneOf1 < ApiModelBase
    # Client-supplied stable id for the stack entry.
    attr_accessor :id

    # Discriminator. `rollout` = percentage-bucket sub-gate.
    attr_accessor :type

    # Human label shown in the dashboard.
    attr_accessor :name

    # Source template id, or `null`.
    attr_accessor :from_template

    # Bucket size in basis points (0–10000 = 0%–100%). `5000` = 50%, `100` = 1%, allows sub-1% precision.
    attr_accessor :rollout_pct

    # Attribute used to hash the caller into a bucket. Defaults to `user.userID`. Use e.g. `accountID` to bucket whole accounts together.
    attr_accessor :bucket_by

    # Per-entry hash salt. Defaults to the gate's salt. Set explicitly to keep two rollouts independent or correlated across gates.
    attr_accessor :salt

    attr_accessor :ramp

    # If `true`, dashboard hides edit controls.
    attr_accessor :locked

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'type' => :'type',
        :'name' => :'name',
        :'from_template' => :'fromTemplate',
        :'rollout_pct' => :'rolloutPct',
        :'bucket_by' => :'bucketBy',
        :'salt' => :'salt',
        :'ramp' => :'ramp',
        :'locked' => :'locked'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'type' => :'String',
        :'name' => :'String',
        :'from_template' => :'String',
        :'rollout_pct' => :'Integer',
        :'bucket_by' => :'String',
        :'salt' => :'String',
        :'ramp' => :'ListGatesResponseDataInnerStackInnerOneOfRamp',
        :'locked' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'from_template',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Shipeasy::Admin::Generated::ListGatesResponseDataInnerStackInnerOneOf1` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Shipeasy::Admin::Generated::ListGatesResponseDataInnerStackInnerOneOf1`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'from_template')
        self.from_template = attributes[:'from_template']
      end

      if attributes.key?(:'rollout_pct')
        self.rollout_pct = attributes[:'rollout_pct']
      else
        self.rollout_pct = nil
      end

      if attributes.key?(:'bucket_by')
        self.bucket_by = attributes[:'bucket_by']
      end

      if attributes.key?(:'salt')
        self.salt = attributes[:'salt']
      end

      if attributes.key?(:'ramp')
        self.ramp = attributes[:'ramp']
      end

      if attributes.key?(:'locked')
        self.locked = attributes[:'locked']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @id.to_s.length < 1
        invalid_properties.push('invalid value for "id", the character length must be greater than or equal to 1.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @rollout_pct.nil?
        invalid_properties.push('invalid value for "rollout_pct", rollout_pct cannot be nil.')
      end

      if @rollout_pct > 10000
        invalid_properties.push('invalid value for "rollout_pct", must be smaller than or equal to 10000.')
      end

      if @rollout_pct < 0
        invalid_properties.push('invalid value for "rollout_pct", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @id.to_s.length < 1
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["rollout"])
      return false unless type_validator.valid?(@type)
      return false if @rollout_pct.nil?
      return false if @rollout_pct > 10000
      return false if @rollout_pct < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      if id.to_s.length < 1
        fail ArgumentError, 'invalid value for "id", the character length must be greater than or equal to 1.'
      end

      @id = id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["rollout"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] rollout_pct Value to be assigned
    def rollout_pct=(rollout_pct)
      if rollout_pct.nil?
        fail ArgumentError, 'rollout_pct cannot be nil'
      end

      if rollout_pct > 10000
        fail ArgumentError, 'invalid value for "rollout_pct", must be smaller than or equal to 10000.'
      end

      if rollout_pct < 0
        fail ArgumentError, 'invalid value for "rollout_pct", must be greater than or equal to 0.'
      end

      @rollout_pct = rollout_pct
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          type == o.type &&
          name == o.name &&
          from_template == o.from_template &&
          rollout_pct == o.rollout_pct &&
          bucket_by == o.bucket_by &&
          salt == o.salt &&
          ramp == o.ramp &&
          locked == o.locked
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, type, name, from_template, rollout_pct, bucket_by, salt, ramp, locked].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
