=begin
#Shipeasy Admin API

#REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Shipeasy::Admin::Generated
  class MetricDirection
    HIGHER_BETTER = "higher_better".freeze
    LOWER_BETTER = "lower_better".freeze
    NEUTRAL = "neutral".freeze

    def self.all_vars
      @all_vars ||= [HIGHER_BETTER, LOWER_BETTER, NEUTRAL].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if MetricDirection.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #MetricDirection"
    end
  end
end
