=begin
#Shipeasy Admin API

#REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Shipeasy::Admin::Generated
  class OpsRunAction
    LINK_PR = "link_pr".freeze
    NOTIFY = "notify".freeze
    STATUS = "status".freeze
    SUPERSEDED = "superseded".freeze

    def self.all_vars
      @all_vars ||= [LINK_PR, NOTIFY, STATUS, SUPERSEDED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if OpsRunAction.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #OpsRunAction"
    end
  end
end
