=begin
#Shipeasy Admin API

#REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Shipeasy::Admin::Generated
  # One structured investigation record on a queue item — the read-only write-up an AI agent produces while working it (findings / blocking question / QA notes), rendered by the cockpit's detail panel.
  class OpsInvestigation < ApiModelBase
    # Investigation record id.
    attr_accessor :id

    # The queue item this record hangs off.
    attr_accessor :feedback_id

    # Which lifecycle stage the record documents — mirrors the investigation-state buckets the cockpit renders. `working` records double as run rows (see `OpsRun`).
    attr_accessor :kind

    # One-line summary of the record, or `null`.
    attr_accessor :summary

    # The agent's full findings write-up (markdown), or `null`.
    attr_accessor :findings

    # A blocking question for the team (markdown), or `null`.
    attr_accessor :question

    # How to verify the fix — QA notes (markdown), or `null`.
    attr_accessor :qa_notes

    # Which agent produced the record (`jarvis` is the in-house assistant; the rest are trigger-connector coding agents), or `null`.
    attr_accessor :agent

    # The model the agent ran on (self-reported), or `null`.
    attr_accessor :model

    # The trigger-connector row id the agent ran through, or `null`.
    attr_accessor :connector_id

    # A PR the record references (e.g. the run's fixing PR), or `null`.
    attr_accessor :pr_number

    # HTML URL of that PR, or `null`.
    attr_accessor :pr_url

    # The files/links the agent inspected, or `null`.
    attr_accessor :sources

    # The agent's self-reported confidence, or `null`.
    attr_accessor :confidence

    # Tokens the run consumed (self-reported), or `null`.
    attr_accessor :tokens_used

    # Run duration in milliseconds, or `null`.
    attr_accessor :duration_ms

    # `draft` records are the agent's scratch state; only `published` ones render in the panel (and are returned by default).
    attr_accessor :visibility

    # ISO-8601 timestamp the work started, or `null`.
    attr_accessor :started_at

    # ISO-8601 timestamp the work finished, or `null`.
    attr_accessor :completed_at

    # The agent-run session id, or `null`.
    attr_accessor :session_id

    # The run's session-page deep link, or `null`. DERIVED (never stored): rebuilt from `sessionId` + the run's trigger connector — Claude's routine id (`?trigger=`), Copilot's repo (`/tasks/`), Cursor/Jules from the id alone. Only `working` run records carry one.
    attr_accessor :session_url

    # Email of the human who acked (run records for a human ack), or `null`.
    attr_accessor :acked_by

    attr_accessor :completed_action

    # ISO-8601 creation timestamp.
    attr_accessor :created_at

    # ISO-8601 last-update timestamp.
    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'feedback_id' => :'feedbackId',
        :'kind' => :'kind',
        :'summary' => :'summary',
        :'findings' => :'findings',
        :'question' => :'question',
        :'qa_notes' => :'qaNotes',
        :'agent' => :'agent',
        :'model' => :'model',
        :'connector_id' => :'connectorId',
        :'pr_number' => :'prNumber',
        :'pr_url' => :'prUrl',
        :'sources' => :'sources',
        :'confidence' => :'confidence',
        :'tokens_used' => :'tokensUsed',
        :'duration_ms' => :'durationMs',
        :'visibility' => :'visibility',
        :'started_at' => :'startedAt',
        :'completed_at' => :'completedAt',
        :'session_id' => :'sessionId',
        :'session_url' => :'sessionUrl',
        :'acked_by' => :'ackedBy',
        :'completed_action' => :'completedAction',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'feedback_id' => :'String',
        :'kind' => :'String',
        :'summary' => :'String',
        :'findings' => :'String',
        :'question' => :'String',
        :'qa_notes' => :'String',
        :'agent' => :'String',
        :'model' => :'String',
        :'connector_id' => :'String',
        :'pr_number' => :'Float',
        :'pr_url' => :'String',
        :'sources' => :'Array<OpsInvestigationSourcesInner>',
        :'confidence' => :'String',
        :'tokens_used' => :'Float',
        :'duration_ms' => :'Float',
        :'visibility' => :'String',
        :'started_at' => :'String',
        :'completed_at' => :'String',
        :'session_id' => :'String',
        :'session_url' => :'String',
        :'acked_by' => :'String',
        :'completed_action' => :'OpsRunActionOrNull',
        :'created_at' => :'String',
        :'updated_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'summary',
        :'findings',
        :'question',
        :'qa_notes',
        :'agent',
        :'model',
        :'connector_id',
        :'pr_number',
        :'pr_url',
        :'sources',
        :'confidence',
        :'tokens_used',
        :'duration_ms',
        :'started_at',
        :'completed_at',
        :'session_id',
        :'session_url',
        :'acked_by',
        :'completed_action',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Shipeasy::Admin::Generated::OpsInvestigation` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Shipeasy::Admin::Generated::OpsInvestigation`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'feedback_id')
        self.feedback_id = attributes[:'feedback_id']
      else
        self.feedback_id = nil
      end

      if attributes.key?(:'kind')
        self.kind = attributes[:'kind']
      else
        self.kind = nil
      end

      if attributes.key?(:'summary')
        self.summary = attributes[:'summary']
      else
        self.summary = nil
      end

      if attributes.key?(:'findings')
        self.findings = attributes[:'findings']
      else
        self.findings = nil
      end

      if attributes.key?(:'question')
        self.question = attributes[:'question']
      else
        self.question = nil
      end

      if attributes.key?(:'qa_notes')
        self.qa_notes = attributes[:'qa_notes']
      else
        self.qa_notes = nil
      end

      if attributes.key?(:'agent')
        self.agent = attributes[:'agent']
      else
        self.agent = nil
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      else
        self.model = nil
      end

      if attributes.key?(:'connector_id')
        self.connector_id = attributes[:'connector_id']
      else
        self.connector_id = nil
      end

      if attributes.key?(:'pr_number')
        self.pr_number = attributes[:'pr_number']
      else
        self.pr_number = nil
      end

      if attributes.key?(:'pr_url')
        self.pr_url = attributes[:'pr_url']
      else
        self.pr_url = nil
      end

      if attributes.key?(:'sources')
        if (value = attributes[:'sources']).is_a?(Array)
          self.sources = value
        end
      else
        self.sources = nil
      end

      if attributes.key?(:'confidence')
        self.confidence = attributes[:'confidence']
      else
        self.confidence = nil
      end

      if attributes.key?(:'tokens_used')
        self.tokens_used = attributes[:'tokens_used']
      else
        self.tokens_used = nil
      end

      if attributes.key?(:'duration_ms')
        self.duration_ms = attributes[:'duration_ms']
      else
        self.duration_ms = nil
      end

      if attributes.key?(:'visibility')
        self.visibility = attributes[:'visibility']
      else
        self.visibility = nil
      end

      if attributes.key?(:'started_at')
        self.started_at = attributes[:'started_at']
      else
        self.started_at = nil
      end

      if attributes.key?(:'completed_at')
        self.completed_at = attributes[:'completed_at']
      else
        self.completed_at = nil
      end

      if attributes.key?(:'session_id')
        self.session_id = attributes[:'session_id']
      else
        self.session_id = nil
      end

      if attributes.key?(:'session_url')
        self.session_url = attributes[:'session_url']
      else
        self.session_url = nil
      end

      if attributes.key?(:'acked_by')
        self.acked_by = attributes[:'acked_by']
      else
        self.acked_by = nil
      end

      if attributes.key?(:'completed_action')
        self.completed_action = attributes[:'completed_action']
      else
        self.completed_action = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @feedback_id.nil?
        invalid_properties.push('invalid value for "feedback_id", feedback_id cannot be nil.')
      end

      if @kind.nil?
        invalid_properties.push('invalid value for "kind", kind cannot be nil.')
      end

      if @visibility.nil?
        invalid_properties.push('invalid value for "visibility", visibility cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @feedback_id.nil?
      return false if @kind.nil?
      kind_validator = EnumAttributeValidator.new('String', ["investigated", "detected", "question", "ready_for_qa", "working", "note"])
      return false unless kind_validator.valid?(@kind)
      agent_validator = EnumAttributeValidator.new('String', ["jarvis", "claude", "cursor", "copilot", "jules"])
      return false unless agent_validator.valid?(@agent)
      confidence_validator = EnumAttributeValidator.new('String', ["low", "medium", "high"])
      return false unless confidence_validator.valid?(@confidence)
      return false if @visibility.nil?
      visibility_validator = EnumAttributeValidator.new('String', ["draft", "published"])
      return false unless visibility_validator.valid?(@visibility)
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] feedback_id Value to be assigned
    def feedback_id=(feedback_id)
      if feedback_id.nil?
        fail ArgumentError, 'feedback_id cannot be nil'
      end

      @feedback_id = feedback_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] kind Object to be assigned
    def kind=(kind)
      validator = EnumAttributeValidator.new('String', ["investigated", "detected", "question", "ready_for_qa", "working", "note"])
      unless validator.valid?(kind)
        fail ArgumentError, "invalid value for \"kind\", must be one of #{validator.allowable_values}."
      end
      @kind = kind
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] agent Object to be assigned
    def agent=(agent)
      validator = EnumAttributeValidator.new('String', ["jarvis", "claude", "cursor", "copilot", "jules"])
      unless validator.valid?(agent)
        fail ArgumentError, "invalid value for \"agent\", must be one of #{validator.allowable_values}."
      end
      @agent = agent
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] confidence Object to be assigned
    def confidence=(confidence)
      validator = EnumAttributeValidator.new('String', ["low", "medium", "high"])
      unless validator.valid?(confidence)
        fail ArgumentError, "invalid value for \"confidence\", must be one of #{validator.allowable_values}."
      end
      @confidence = confidence
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] visibility Object to be assigned
    def visibility=(visibility)
      validator = EnumAttributeValidator.new('String', ["draft", "published"])
      unless validator.valid?(visibility)
        fail ArgumentError, "invalid value for \"visibility\", must be one of #{validator.allowable_values}."
      end
      @visibility = visibility
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          feedback_id == o.feedback_id &&
          kind == o.kind &&
          summary == o.summary &&
          findings == o.findings &&
          question == o.question &&
          qa_notes == o.qa_notes &&
          agent == o.agent &&
          model == o.model &&
          connector_id == o.connector_id &&
          pr_number == o.pr_number &&
          pr_url == o.pr_url &&
          sources == o.sources &&
          confidence == o.confidence &&
          tokens_used == o.tokens_used &&
          duration_ms == o.duration_ms &&
          visibility == o.visibility &&
          started_at == o.started_at &&
          completed_at == o.completed_at &&
          session_id == o.session_id &&
          session_url == o.session_url &&
          acked_by == o.acked_by &&
          completed_action == o.completed_action &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, feedback_id, kind, summary, findings, question, qa_notes, agent, model, connector_id, pr_number, pr_url, sources, confidence, tokens_used, duration_ms, visibility, started_at, completed_at, session_id, session_url, acked_by, completed_action, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
