=begin
#Shipeasy Admin API

#REST API for managing feature gates, experiments, configs, universes, and killswitches in a Shipeasy project. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Mint admin keys via `POST /api/admin/keys` with `type: \"admin\"`. Keys expire after 90 days; rotate with the `revoke` action.

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Shipeasy::Admin::Generated
  # Update-metric variant that replaces the query with a typed `query_ir`.
  class UpdateMetricWithQueryIr < ApiModelBase
    # What a human calls the metric — \"Checkout revenue\" beside the `checkout.revenue` that identifies it. Unlike `name` it is free text, it is editable, and nothing addresses the metric by it: the dashboard leads with it and falls back to `name` when it is absent, so a metric nobody named simply reads as its key. Send `null` to clear it.
    attr_accessor :display_name

    # Optional folder name grouping items in the dashboard. Alphanumeric, `_` or `-` (no `/`). Part of the SDK lookup key (`<folder>/<name>`).
    attr_accessor :folder

    # Source event the query reads from.
    attr_accessor :event_name

    attr_accessor :query_ir

    # Winsorise percentile (1–99) to clamp outliers. Defaults to 99.
    attr_accessor :winsorize_pct

    # Default minimum effect of interest (relative, 0–1) — the smallest change in this metric worth acting on, used as the power-planning baseline. Intrinsic to the metric; an experiment overrides it per-attachment with `min_effect_of_interest` when a specific decision has a different cost/risk bar. `null` to omit.
    attr_accessor :default_min_effect_of_interest

    attr_accessor :direction

    # Optional gate name (a `targeting`-type flag). Only callers that pass the gate are enrolled in the experiment.
    attr_accessor :unit

    attr_accessor :display

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'display_name' => :'display_name',
        :'folder' => :'folder',
        :'event_name' => :'event_name',
        :'query_ir' => :'query_ir',
        :'winsorize_pct' => :'winsorize_pct',
        :'default_min_effect_of_interest' => :'default_min_effect_of_interest',
        :'direction' => :'direction',
        :'unit' => :'unit',
        :'display' => :'display'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'display_name' => :'String',
        :'folder' => :'String',
        :'event_name' => :'String',
        :'query_ir' => :'QueryIr',
        :'winsorize_pct' => :'Integer',
        :'default_min_effect_of_interest' => :'Float',
        :'direction' => :'MetricDirection',
        :'unit' => :'String',
        :'display' => :'MetricDisplayConfig'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'display_name',
        :'folder',
        :'default_min_effect_of_interest',
        :'unit',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Shipeasy::Admin::Generated::UpdateMetricWithQueryIr` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Shipeasy::Admin::Generated::UpdateMetricWithQueryIr`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'display_name')
        self.display_name = attributes[:'display_name']
      end

      if attributes.key?(:'folder')
        self.folder = attributes[:'folder']
      end

      if attributes.key?(:'event_name')
        self.event_name = attributes[:'event_name']
      end

      if attributes.key?(:'query_ir')
        self.query_ir = attributes[:'query_ir']
      else
        self.query_ir = nil
      end

      if attributes.key?(:'winsorize_pct')
        self.winsorize_pct = attributes[:'winsorize_pct']
      else
        self.winsorize_pct = 99
      end

      if attributes.key?(:'default_min_effect_of_interest')
        self.default_min_effect_of_interest = attributes[:'default_min_effect_of_interest']
      end

      if attributes.key?(:'direction')
        self.direction = attributes[:'direction']
      else
        self.direction = 'higher_better'
      end

      if attributes.key?(:'unit')
        self.unit = attributes[:'unit']
      end

      if attributes.key?(:'display')
        self.display = attributes[:'display']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@folder.nil? && @folder.to_s.length > 256
        invalid_properties.push('invalid value for "folder", the character length must be smaller than or equal to 256.')
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_-]+$/)
      if !@folder.nil? && @folder !~ pattern
        invalid_properties.push("invalid value for \"folder\", must conform to the pattern #{pattern}.")
      end

      if !@event_name.nil? && @event_name.to_s.length < 1
        invalid_properties.push('invalid value for "event_name", the character length must be greater than or equal to 1.')
      end

      if @query_ir.nil?
        invalid_properties.push('invalid value for "query_ir", query_ir cannot be nil.')
      end

      if !@winsorize_pct.nil? && @winsorize_pct > 99
        invalid_properties.push('invalid value for "winsorize_pct", must be smaller than or equal to 99.')
      end

      if !@winsorize_pct.nil? && @winsorize_pct < 1
        invalid_properties.push('invalid value for "winsorize_pct", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@folder.nil? && @folder.to_s.length > 256
      return false if !@folder.nil? && @folder !~ Regexp.new(/^[a-zA-Z0-9_-]+$/)
      return false if !@event_name.nil? && @event_name.to_s.length < 1
      return false if @query_ir.nil?
      return false if !@winsorize_pct.nil? && @winsorize_pct > 99
      return false if !@winsorize_pct.nil? && @winsorize_pct < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] folder Value to be assigned
    def folder=(folder)
      if !folder.nil? && folder.to_s.length > 256
        fail ArgumentError, 'invalid value for "folder", the character length must be smaller than or equal to 256.'
      end

      pattern = Regexp.new(/^[a-zA-Z0-9_-]+$/)
      if !folder.nil? && folder !~ pattern
        fail ArgumentError, "invalid value for \"folder\", must conform to the pattern #{pattern}."
      end

      @folder = folder
    end

    # Custom attribute writer method with validation
    # @param [Object] event_name Value to be assigned
    def event_name=(event_name)
      if event_name.nil?
        fail ArgumentError, 'event_name cannot be nil'
      end

      if event_name.to_s.length < 1
        fail ArgumentError, 'invalid value for "event_name", the character length must be greater than or equal to 1.'
      end

      @event_name = event_name
    end

    # Custom attribute writer method with validation
    # @param [Object] query_ir Value to be assigned
    def query_ir=(query_ir)
      if query_ir.nil?
        fail ArgumentError, 'query_ir cannot be nil'
      end

      @query_ir = query_ir
    end

    # Custom attribute writer method with validation
    # @param [Object] winsorize_pct Value to be assigned
    def winsorize_pct=(winsorize_pct)
      if winsorize_pct.nil?
        fail ArgumentError, 'winsorize_pct cannot be nil'
      end

      if winsorize_pct > 99
        fail ArgumentError, 'invalid value for "winsorize_pct", must be smaller than or equal to 99.'
      end

      if winsorize_pct < 1
        fail ArgumentError, 'invalid value for "winsorize_pct", must be greater than or equal to 1.'
      end

      @winsorize_pct = winsorize_pct
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          display_name == o.display_name &&
          folder == o.folder &&
          event_name == o.event_name &&
          query_ir == o.query_ir &&
          winsorize_pct == o.winsorize_pct &&
          default_min_effect_of_interest == o.default_min_effect_of_interest &&
          direction == o.direction &&
          unit == o.unit &&
          display == o.display
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [display_name, folder, event_name, query_ir, winsorize_pct, default_min_effect_of_interest, direction, unit, display].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
