=begin
#Shipeasy Admin API (SDK admin subset)

#Lean subset of the Shipeasy admin API vendored into the server SDKs to build the optional AdminClient. Generated by scripts/sdk-spec/prune.mjs from the canonical spec — do not hand-edit. Groups: ops-public-ticket, killswitch-switches, flag-whitelist.

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Shipeasy::Admin::Generated
  # Content + triage update for a `bug` item (`PATCH /api/admin/ops/{handle}` when the item is a bug).
  class UpdateBugRequest < ApiModelBase
    # New bug title (no leading/trailing whitespace).
    attr_accessor :title

    # Updated reproduction steps.
    attr_accessor :steps_to_reproduce

    # Updated actual result.
    attr_accessor :actual_result

    # Updated expected result.
    attr_accessor :expected_result

    attr_accessor :status

    attr_accessor :priority

    # Link (or, when `null`, unlink) a GitHub pull request to this bug.
    attr_accessor :github_pr_number

    attr_accessor :notify

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'title' => :'title',
        :'steps_to_reproduce' => :'stepsToReproduce',
        :'actual_result' => :'actualResult',
        :'expected_result' => :'expectedResult',
        :'status' => :'status',
        :'priority' => :'priority',
        :'github_pr_number' => :'githubPrNumber',
        :'notify' => :'notify'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'title' => :'String',
        :'steps_to_reproduce' => :'String',
        :'actual_result' => :'String',
        :'expected_result' => :'String',
        :'status' => :'OpsItemStatus',
        :'priority' => :'OpsItemPriorityOrNull',
        :'github_pr_number' => :'Integer',
        :'notify' => :'OpsItemNotifyOrNull'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'priority',
        :'github_pr_number',
        :'notify'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Shipeasy::Admin::Generated::UpdateBugRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Shipeasy::Admin::Generated::UpdateBugRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'steps_to_reproduce')
        self.steps_to_reproduce = attributes[:'steps_to_reproduce']
      end

      if attributes.key?(:'actual_result')
        self.actual_result = attributes[:'actual_result']
      end

      if attributes.key?(:'expected_result')
        self.expected_result = attributes[:'expected_result']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'priority')
        self.priority = attributes[:'priority']
      end

      if attributes.key?(:'github_pr_number')
        self.github_pr_number = attributes[:'github_pr_number']
      end

      if attributes.key?(:'notify')
        self.notify = attributes[:'notify']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@title.nil? && @title.to_s.length > 200
        invalid_properties.push('invalid value for "title", the character length must be smaller than or equal to 200.')
      end

      if !@title.nil? && @title.to_s.length < 1
        invalid_properties.push('invalid value for "title", the character length must be greater than or equal to 1.')
      end

      pattern = Regexp.new(/^\S(.*\S)?$/)
      if !@title.nil? && @title !~ pattern
        invalid_properties.push("invalid value for \"title\", must conform to the pattern #{pattern}.")
      end

      if !@steps_to_reproduce.nil? && @steps_to_reproduce.to_s.length > 8000
        invalid_properties.push('invalid value for "steps_to_reproduce", the character length must be smaller than or equal to 8000.')
      end

      if !@actual_result.nil? && @actual_result.to_s.length > 8000
        invalid_properties.push('invalid value for "actual_result", the character length must be smaller than or equal to 8000.')
      end

      if !@expected_result.nil? && @expected_result.to_s.length > 8000
        invalid_properties.push('invalid value for "expected_result", the character length must be smaller than or equal to 8000.')
      end

      if !@github_pr_number.nil? && @github_pr_number < 1
        invalid_properties.push('invalid value for "github_pr_number", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@title.nil? && @title.to_s.length > 200
      return false if !@title.nil? && @title.to_s.length < 1
      return false if !@title.nil? && @title !~ Regexp.new(/^\S(.*\S)?$/)
      return false if !@steps_to_reproduce.nil? && @steps_to_reproduce.to_s.length > 8000
      return false if !@actual_result.nil? && @actual_result.to_s.length > 8000
      return false if !@expected_result.nil? && @expected_result.to_s.length > 8000
      return false if !@github_pr_number.nil? && @github_pr_number < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if title.nil?
        fail ArgumentError, 'title cannot be nil'
      end

      if title.to_s.length > 200
        fail ArgumentError, 'invalid value for "title", the character length must be smaller than or equal to 200.'
      end

      if title.to_s.length < 1
        fail ArgumentError, 'invalid value for "title", the character length must be greater than or equal to 1.'
      end

      pattern = Regexp.new(/^\S(.*\S)?$/)
      if title !~ pattern
        fail ArgumentError, "invalid value for \"title\", must conform to the pattern #{pattern}."
      end

      @title = title
    end

    # Custom attribute writer method with validation
    # @param [Object] steps_to_reproduce Value to be assigned
    def steps_to_reproduce=(steps_to_reproduce)
      if steps_to_reproduce.nil?
        fail ArgumentError, 'steps_to_reproduce cannot be nil'
      end

      if steps_to_reproduce.to_s.length > 8000
        fail ArgumentError, 'invalid value for "steps_to_reproduce", the character length must be smaller than or equal to 8000.'
      end

      @steps_to_reproduce = steps_to_reproduce
    end

    # Custom attribute writer method with validation
    # @param [Object] actual_result Value to be assigned
    def actual_result=(actual_result)
      if actual_result.nil?
        fail ArgumentError, 'actual_result cannot be nil'
      end

      if actual_result.to_s.length > 8000
        fail ArgumentError, 'invalid value for "actual_result", the character length must be smaller than or equal to 8000.'
      end

      @actual_result = actual_result
    end

    # Custom attribute writer method with validation
    # @param [Object] expected_result Value to be assigned
    def expected_result=(expected_result)
      if expected_result.nil?
        fail ArgumentError, 'expected_result cannot be nil'
      end

      if expected_result.to_s.length > 8000
        fail ArgumentError, 'invalid value for "expected_result", the character length must be smaller than or equal to 8000.'
      end

      @expected_result = expected_result
    end

    # Custom attribute writer method with validation
    # @param [Object] github_pr_number Value to be assigned
    def github_pr_number=(github_pr_number)
      if !github_pr_number.nil? && github_pr_number < 1
        fail ArgumentError, 'invalid value for "github_pr_number", must be greater than or equal to 1.'
      end

      @github_pr_number = github_pr_number
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          title == o.title &&
          steps_to_reproduce == o.steps_to_reproduce &&
          actual_result == o.actual_result &&
          expected_result == o.expected_result &&
          status == o.status &&
          priority == o.priority &&
          github_pr_number == o.github_pr_number &&
          notify == o.notify
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [title, steps_to_reproduce, actual_result, expected_result, status, priority, github_pr_number, notify].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
