=begin
#Shipeasy Admin API (SDK admin subset)

#Lean subset of the Shipeasy admin API vendored into the server SDKs to build the optional AdminClient. Generated by scripts/sdk-spec/prune.mjs from the canonical spec — do not hand-edit. Groups: ops-public-ticket, killswitch-switches, flag-whitelist.

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

module Shipeasy::Admin::Generated
  VERSION = '1.0.0'
end
