=begin
#Shipeasy Admin API (server-SDK surface)

#The slice of the Shipeasy admin API that the published server SDKs expose as their optional `AdminClient`. Authenticate with an admin SDK key (`Authorization: Bearer sdk_admin_…`) and scope every request to a project via the `X-Project-Id` header.  Three capabilities, nothing else:  - **File a public ticket** — a bug or a feature request onto the project's ops queue. - **Toggle a kill switch** — flip the switch itself, or one of its named sub-switches, on one environment. - **Manage a flag's whitelist** — read, replace, add to, or remove from the allowlist that admits specific identities ahead of every targeting rule.  Everything else in the admin API is reachable through the Shipeasy CLI and MCP server, which speak the complete contract (`openapi.yaml`).

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

# Common files
require 'shipeasy_admin/api_client'
require 'shipeasy_admin/api_error'
require 'shipeasy_admin/api_model_base'
require 'shipeasy_admin/version'
require 'shipeasy_admin/configuration'

# Models
require 'shipeasy_admin/models/add_to_gate_whitelist_request'
require 'shipeasy_admin/models/create_public_bug_request'
require 'shipeasy_admin/models/create_public_feature_request_request'
require 'shipeasy_admin/models/create_public_ticket_response'
require 'shipeasy_admin/models/env'
require 'shipeasy_admin/models/error'
require 'shipeasy_admin/models/error_code'
require 'shipeasy_admin/models/gate_whitelist'
require 'shipeasy_admin/models/gate_whitelist_attr'
require 'shipeasy_admin/models/killswitch_value'
require 'shipeasy_admin/models/notification_target'
require 'shipeasy_admin/models/notification_target_slack_channel'
require 'shipeasy_admin/models/ops_item_priority'
require 'shipeasy_admin/models/ops_item_status'
require 'shipeasy_admin/models/remove_from_gate_whitelist_request'
require 'shipeasy_admin/models/set_gate_whitelist_request'
require 'shipeasy_admin/models/toggle_killswitch_request'
require 'shipeasy_admin/models/toggle_killswitch_response'

# APIs
require 'shipeasy_admin/api/flags_api'
require 'shipeasy_admin/api/killswitch_api'
require 'shipeasy_admin/api/ops_api'

module Shipeasy::Admin::Generated
  class << self
    # Customize default settings for the SDK using block.
    #   Shipeasy::Admin::Generated.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
