=begin
#Shipeasy Admin API (SDK admin subset)

#Lean subset of the Shipeasy admin API vendored into the server SDKs to build the optional AdminClient. Generated by scripts/sdk-spec/prune.mjs from the canonical spec — do not hand-edit. Groups: ops-public-ticket, killswitch-switches, flag-whitelist.

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

# Common files
require 'shipeasy_admin/api_client'
require 'shipeasy_admin/api_error'
require 'shipeasy_admin/api_model_base'
require 'shipeasy_admin/version'
require 'shipeasy_admin/configuration'

# Models
require 'shipeasy_admin/models/connector_data'
require 'shipeasy_admin/models/create_bug_request'
require 'shipeasy_admin/models/create_feature_request_request'
require 'shipeasy_admin/models/create_ops_comment_request'
require 'shipeasy_admin/models/create_ops_comment_response'
require 'shipeasy_admin/models/create_ops_item_request'
require 'shipeasy_admin/models/create_ops_item_response'
require 'shipeasy_admin/models/env'
require 'shipeasy_admin/models/error'
require 'shipeasy_admin/models/error_code'
require 'shipeasy_admin/models/gate_api_row'
require 'shipeasy_admin/models/gate_api_row_enabled'
require 'shipeasy_admin/models/gate_api_row_rules_inner'
require 'shipeasy_admin/models/gate_api_row_stack_inner'
require 'shipeasy_admin/models/gate_api_row_stack_inner_one_of'
require 'shipeasy_admin/models/gate_api_row_stack_inner_one_of1'
require 'shipeasy_admin/models/gate_api_row_stack_inner_one_of_ramp'
require 'shipeasy_admin/models/get_killswitch_response'
require 'shipeasy_admin/models/get_killswitch_response_envs_value'
require 'shipeasy_admin/models/get_ops_item_response'
require 'shipeasy_admin/models/github_connector_data'
require 'shipeasy_admin/models/github_connector_data_issue'
require 'shipeasy_admin/models/github_pr_link'
require 'shipeasy_admin/models/list_gates_response'
require 'shipeasy_admin/models/list_killswitches_response'
require 'shipeasy_admin/models/list_killswitches_response_data_inner'
require 'shipeasy_admin/models/list_ops_comments_response'
require 'shipeasy_admin/models/list_ops_items_response_inner'
require 'shipeasy_admin/models/measure_plan_resource'
require 'shipeasy_admin/models/measure_plan_step'
require 'shipeasy_admin/models/notification_target'
require 'shipeasy_admin/models/notification_target_slack_channel'
require 'shipeasy_admin/models/ops_alert_context'
require 'shipeasy_admin/models/ops_alert_metric_summary'
require 'shipeasy_admin/models/ops_alert_rule_summary'
require 'shipeasy_admin/models/ops_browser_context'
require 'shipeasy_admin/models/ops_comment'
require 'shipeasy_admin/models/ops_comment_author_type'
require 'shipeasy_admin/models/ops_error_context'
require 'shipeasy_admin/models/ops_investigation_state'
require 'shipeasy_admin/models/ops_item_attachment'
require 'shipeasy_admin/models/ops_item_context'
require 'shipeasy_admin/models/ops_item_context_error_chart'
require 'shipeasy_admin/models/ops_item_context_error_chart_series_inner'
require 'shipeasy_admin/models/ops_item_notify_or_null'
require 'shipeasy_admin/models/ops_item_owner'
require 'shipeasy_admin/models/ops_item_owner_agent'
require 'shipeasy_admin/models/ops_item_owner_user'
require 'shipeasy_admin/models/ops_item_priority'
require 'shipeasy_admin/models/ops_item_priority_or_null'
require 'shipeasy_admin/models/ops_item_related'
require 'shipeasy_admin/models/ops_item_status'
require 'shipeasy_admin/models/ops_measure_plan_context'
require 'shipeasy_admin/models/ops_run'
require 'shipeasy_admin/models/ops_run_action'
require 'shipeasy_admin/models/ops_run_action_or_null'
require 'shipeasy_admin/models/set_killswitch_switch_request'
require 'shipeasy_admin/models/set_killswitch_switch_response'
require 'shipeasy_admin/models/slack_connector_data'
require 'shipeasy_admin/models/slack_connector_data_message'
require 'shipeasy_admin/models/unset_killswitch_switch_request'
require 'shipeasy_admin/models/unset_killswitch_switch_response'
require 'shipeasy_admin/models/update_bug_request'
require 'shipeasy_admin/models/update_feature_request_request'
require 'shipeasy_admin/models/update_gate_request'
require 'shipeasy_admin/models/update_gate_response'
require 'shipeasy_admin/models/update_ops_item_request'
require 'shipeasy_admin/models/update_ops_item_response'
require 'shipeasy_admin/models/update_ops_item_status_request'

# APIs
require 'shipeasy_admin/api/comments_api'
require 'shipeasy_admin/api/flags_api'
require 'shipeasy_admin/api/killswitch_api'
require 'shipeasy_admin/api/ops_api'

module Shipeasy::Admin::Generated
  class << self
    # Customize default settings for the SDK using block.
    #   Shipeasy::Admin::Generated.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
