#!/usr/bin/env ruby
# frozen_string_literal: true

# Generate README.md from the docs in `docs/`.
#
# The docs are the single source of truth. This assembles a polished README —
# badges, install + quickstart (pulled from the doc pages), a documentation
# table, and a testing section — so the README never drifts from the docs.
#
# Run after editing anything under `docs/`:
#
#     ruby scripts/gen_readme.rb     # or: rake readme
#
# CI re-runs it and asserts no diff to catch drift. The generator is idempotent.

require "json"

ROOT = File.expand_path("..", __dir__)
DOCS = File.join(ROOT, "docs")

OWNER = "shipeasy-ai"
REPO  = "sdk-ruby"
GEM   = "shipeasy-sdk"
BLOB  = "https://github.com/#{OWNER}/#{REPO}/blob/main"
PAGES_SITE = "https://#{OWNER}.github.io/#{REPO}"

# One-line "what" for the docs table, keyed by manifest page key. Falls back to
# the page's own lead paragraph when not listed here.
PAGE_BLURB = {
  "overview"        => "The `Shipeasy.configure` + `Client.new(user)` model.",
  "installation"    => "Install, frameworks (Rails / Sinatra / serverless), `configure` wiring.",
  "configuration"   => "Keys, `attributes`, one-shot vs poll, every option.",
  "flags"           => "`get_flag`, `get_flag_detail`, defaults.",
  "configs"         => "`get_config`, typed decode, defaults.",
  "killswitches"    => "`get_killswitch`, named switches.",
  "experiments"     => "`get_experiment`, `log_exposure`, `track`.",
  "i18n"            => "Rails view helpers + the SSR loader tag.",
  "error-reporting" => "`see()` structured error reporting.",
  "testing"         => "`configure_for_testing` / `configure_for_offline`, overrides.",
  "openfeature"     => "`Shipeasy::OpenFeature::Provider` (OpenFeature server provider).",
  "advanced"        => "Anon-id middleware, private attributes, sticky bucketing, SSR.",
}.freeze

PAGE_TITLE = {
  "overview"        => "Overview",
  "installation"    => "Installation",
  "configuration"   => "Configuration",
  "flags"           => "Feature flags",
  "configs"         => "Dynamic configs",
  "killswitches"    => "Kill switches",
  "experiments"     => "Experiments",
  "i18n"            => "Internationalization",
  "error-reporting" => "Error reporting",
  "testing"         => "Testing",
  "openfeature"     => "OpenFeature",
  "advanced"        => "Advanced",
}.freeze

def read(rel)
  File.read(File.join(DOCS, rel))
end

# Rewrite relative `(page.md)` links (as they appear inside docs/pages/) to
# absolute GitHub blob URLs, so pulled prose links work from the repo root.
def absolutize(text)
  text.gsub(%r{\]\((?!https?://|/)([\w./-]+?\.md)(#[\w-]+)?\)}) do
    "](#{BLOB}/docs/pages/#{Regexp.last_match(1)}#{Regexp.last_match(2)})"
  end
end

def first_code(md, lang)
  m = md.match(/```#{lang}\n(.*?)```/m)
  m ? m[1].rstrip : ""
end

def lead_paragraph_md(md)
  out = []
  started = false
  md.each_line do |ln|
    unless started
      started = ln.start_with?("# ")
      next
    end
    s = ln.strip
    if s.empty?
      break unless out.empty?

      next
    end
    if s.start_with?("#", "```", ">", "|", "-", "<")
      break unless out.empty?

      next
    end
    out << s
  end
  out.join(" ").gsub(/\s+/, " ").strip
end

def lead_paragraph(md)
  text = lead_paragraph_md(md)
  text = text.gsub(/`([^`]+)`/, '\1')
  text = text.gsub(/\*\*(.+?)\*\*/, '\1')
  text.gsub(/\[(.+?)\]\([^)]*\)/, '\1').strip
end

manifest = JSON.parse(read("manifest.json"))
pages = manifest["pages"]
sdk = manifest["sdk"]

install   = first_code(read("pages/installation.md"), "ruby")
install   = %(gem "#{GEM}") if install.empty?
quickstart = first_code(read("pages/overview.md"), "ruby")
testing_md   = read("pages/testing.md")
testing_lead = absolutize(lead_paragraph_md(testing_md))
testing_code = first_code(testing_md, "ruby")

rows = pages.keys.map do |key|
  title = PAGE_TITLE.fetch(key, key.split("-").map(&:capitalize).join(" "))
  blurb = PAGE_BLURB[key] || lead_paragraph(read(pages[key]))
  blurb = "#{blurb[0, 87].rstrip}…" if blurb.length > 90
  "| [#{title}](#{BLOB}/docs/pages/#{key}.md) | #{blurb} |"
end
docs_table = rows.join("\n")

readme = <<~MD
  <!--
    This file is GENERATED by scripts/gen_readme.rb from docs/.
    Do NOT edit by hand — edit the docs, then run: ruby scripts/gen_readme.rb
  -->

  # shipeasy-sdk (Ruby)

  [![Tests](https://github.com/#{OWNER}/#{REPO}/actions/workflows/test.yml/badge.svg)](https://github.com/#{OWNER}/#{REPO}/actions/workflows/test.yml)
  [![Gem](https://img.shields.io/gem/v/#{GEM}.svg)](https://rubygems.org/gems/#{GEM})
  [![Ruby](https://img.shields.io/badge/ruby-%3E%3D%203.0-CC342D.svg)](https://www.ruby-lang.org/)

  Server SDK for [Shipeasy](https://shipeasy.ai) — **feature flags, dynamic
  configs, kill switches, A/B experiments, and metric tracking**, with Rails i18n
  view helpers. Server-key only; never embed in a browser.

  > 📚 **Full documentation:** **<#{PAGES_SITE}/>** — also browsable under
  > [`docs/`](#{BLOB}/docs). This README is generated from those docs.

  > Source-available under the [Shipeasy-SAL 1.0](./LICENSE).

  ## 🤖 Using an AI agent?

  This SDK ships an installable **agent skill** — a copy-paste-ready guide to
  `Shipeasy.configure` + `Client.new(user)`, testing, experiments, error
  reporting, and more, with links the agent can pull for deeper docs:

  - **Skill:** [`docs/skill/SKILL.md`](#{BLOB}/docs/skill/SKILL.md) · raw:
    `#{PAGES_SITE}/skill/SKILL.md`
  - **Install it** (ships with the gem — no network):
    `shipeasy-skill install` → `.claude/skills/shipeasy-#{sdk}/SKILL.md`
    (or via the Shipeasy CLI: `shipeasy docs skill --sdk #{sdk} --install`)

  **Humans:** you can copy that skill straight into your own project's agent skills
  directory (e.g. `.claude/skills/shipeasy-#{sdk}/SKILL.md`) so your coding agent
  always uses the correct Shipeasy patterns. Every doc page and snippet is also
  fetchable by URL — start from the manifest at `#{PAGES_SITE}/manifest.json`.

  ## Install

  ```ruby
  #{install}
  ```

  Requires Ruby 3.0+. Per-framework setup (Rails / Sinatra / serverless) and the
  anon-id middleware are on the [Installation](#{BLOB}/docs/pages/installation.md) page.

  ## Quickstart — `configure` once, then `Client.new(user)` per request

  ```ruby
  #{quickstart}
  ```

  Constructing `Shipeasy::Client.new(user)` before `Shipeasy.configure` raises
  `Shipeasy::Error`.

  ## Documentation

  | Page | What |
  | --- | --- |
  #{docs_table}

  Copy-paste snippets live under [`docs/snippets/`](#{BLOB}/docs/snippets)
  (release · metrics · i18n · ops); an installable agent skill is at
  [`docs/skill/SKILL.md`](#{BLOB}/docs/skill/SKILL.md).

  ## Testing

  #{testing_lead}

  ```ruby
  #{testing_code}
  ```

  More — the on-the-spot override helpers and a working example
  `shipeasy-snapshot.json` — on the [Testing](#{BLOB}/docs/pages/testing.md) page.

  ## License

  [Shipeasy-SAL 1.0](./LICENSE) — source-available, non-commercial-use, permitted
  as a Shipeasy client. Evaluation is tested against the cross-language
  MurmurHash3 vectors in `experiment-platform/04-evaluation.md`.
MD

File.write(File.join(ROOT, "README.md"), readme)
puts "Wrote README.md (#{readme.bytesize} bytes) from #{pages.size} doc pages."
